# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-devel
bioc_check: true

# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master

# Test code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  slack:
    secure: AFznGl/V208+GM3bsDy+DCG9Jr1sdGxHEHesl0GUgCoUlidgZ2XUX9gxE3ZtWkfmqo+C4Awy+XL1zPWU+Z62RHm4GtIrRJpjba32/3EglHW63dCgbV73sj/8tgIcI02jEaM2hL98D66nv2QNNoEU0987Hde6Os0lhg0nirnVDNM=

